version: '3'
services:
  app:
    build:
      context: .
      args:
        - VERSION=$MINECRAFT_VERSION
    environment:
      EULA: $EULA # TRUE or FALSE
      MAX_MEMORY: $MINECRAFT_MAX_MEMORY
      MIN_MEMORY: $MINECRAFT_MIN_MEMORY
    volumes:
      - $SPIGOT_DIR:/opt/spigot
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "25575:25575/udp"
    stop_grace_period: "30s"
