---

- name: spigot installer
  hosts: all
  tasks:
    - name: install utils
      yum:
        name=git
      become: yes
    - name: create repo
      file:
        path: /Repositories/gretel
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0777
      become: yes
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/shokkunrf/gretel.git
        dest: /Repositories/gretel
    - name: setup gretel
      shell: bash /Repositories/gretel/setup.sh install {{ minecraft_version }}
      args:
        chdir: /Repositories/gretel
      poll: 30
      async: 900
